version: "3.9"
services:
  sqlserver:
    container_name: sqlserver
    image: mcr.microsoft.com/mssql/server:${SQLSERVER_IMAGE_VERSION_TAG}
    ports:
      - ${SQLSERVER_EXTERNAL_PORT}:1433/tcp
    environment:
      ACCEPT_EULA: Y
      MSSQL_PID: Express
      SA_PASSWORD: ${SQLSERVER_SA_PASSWORD}
      DATABASE: ${SQLSERVER_DATABASE}
    command: /bin/bash ./docker-entrypoint.sh
    volumes:
      - ./docker-entrypoint.sqlserver.sh:/docker-entrypoint.sh
  engine:
    container_name: processengine
    image: 5minds/atlas_engine_fullstack_server:${ENGINE_IMAGE_VERSION_TAG}
    ports:
      - ${ENGINE_PORT_EXTERNAL}:80
    environment:
      application__name: ${ENGINE_APPLICATION_NAME}
      httpServer__port: 80
      NODE_OPTIONS: --max_old_space_size=8000
      CONFIG_PATH: /mnt/config/mssql.json
      database__host: sqlserver
      database__username: sa
      database__password: ${SQLSERVER_SA_PASSWORD}
      database__database: ${SQLSERVER_DATABASE}
      database__port: 1433
    depends_on:
        - sqlserver
    entrypoint: "/bin/sh ./docker-entrypoint.sh --extensions-dir=/extensions --seed-dir=/processes"
    volumes:
      - ./mssql.json:/mnt/config/mssql.json
      - ./docker-entrypoint.engine.sh:/docker-entrypoint.sh
      - ./processes:/processes
      - ./extensions:/extensions